# Generated by Django 4.0.6 on 2022-08-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('debut', models.DateTimeField(null=True)),
                ('country', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='name',
        ),
        migrations.AddField(
            model_name='genre',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
