# Generated by Django 3.2.13 on 2022-09-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='priorty',
            new_name='priority',
        ),
    ]
